/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-06-08 03:46:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class searchview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1710997874000L));
    _jspx_dependants.put("jar:file:/C:/Users/dsf4a/OneDrive/바탕%20화면/JSP-PROJECT-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSP-PROJECT/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602841572000L));
    _jspx_dependants.put("jar:file:/C:/Users/dsf4a/OneDrive/바탕%20화면/JSP-PROJECT-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSP-PROJECT/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>KSW 책 검색 페이지</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/header.css\">\n");
      out.write("<style>\n");
      out.write("/* 페이지 전체 스타일 */\n");
      out.write("body {\n");
      out.write("	font-family: 'Arial', sans-serif;\n");
      out.write("	background-color: #f5f5f5;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 검색 양식 스타일 */\n");
      out.write("#searchFrm {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#keyword {\n");
      out.write("	flex-grow: 1;\n");
      out.write("	padding: 10px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	border: 1px solid #ccc;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("	width: 300px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchBtn {\n");
      out.write("	padding: 10px 20px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	background-color: #007bff;\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchBtn:hover {\n");
      out.write("	background-color: #0056b3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 검색 결과 및 페이지네이션 컨테이너 스타일 */\n");
      out.write(".row, #pagination {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	flex-wrap: wrap;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 페이지네이션 버튼 스타일 */\n");
      out.write(".page-btn {\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	border: 1px solid #ddd;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	margin: 10px 5px;\n");
      out.write("	background-color: #fff;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 페이지네이션 버튼 스타일 */\n");
      out.write(".page-btn1 {\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	border: 1px solid #ddd;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	margin: 10px 5px;\n");
      out.write("	background-color: #fff;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".page-btn:hover, .page-btn.active {\n");
      out.write("	background-color: #007bff;\n");
      out.write("	color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 추가적인 전반적인 스타일 조정 */\n");
      out.write("#pagination {\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 검색 결과 그리드 스타일 */\n");
      out.write("#searchResult {\n");
      out.write("	display: grid;\n");
      out.write("	grid-template-columns: repeat(4, 1fr); /* 4개의 컬럼으로 나눔 */\n");
      out.write("	gap: 20px; /* 그리드 아이템 간의 간격 */\n");
      out.write("	padding: 20px; /* 컨테이너의 내부 여백 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 검색 결과 상세 스타일 */\n");
      out.write("#searchResult ul {\n");
      out.write("	margin: 0; /* 기존 마진 제거 */\n");
      out.write("	padding: 10px; /* 패딩 유지 */\n");
      out.write("	background-color: #ffffff;\n");
      out.write("	border: 1px solid #dddddd;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n");
      out.write("	overflow: hidden;\n");
      out.write("	transition: box-shadow 0.3s ease;\n");
      out.write("	display: flex; /* 이미지와 텍스트를 세로로 정렬 */\n");
      out.write("	flex-direction: column; /* 컨텐츠를 세로로 정렬 */\n");
      out.write("	align-items: center; /* 가운데 정렬 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchResult ul:hover {\n");
      out.write("	box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchResult img {\n");
      out.write("	width: 100%; /* 이미지 너비를 ul에 맞춤 */\n");
      out.write("	height: 50%; /* 이미지 비율 유지 */\n");
      out.write("	max-width: 150px; /* 최대 너비 설정 */\n");
      out.write("	margin-bottom: 10px; /* 이미지와 텍스트 사이의 마진 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchResult li {\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 8px 12px;\n");
      out.write("	border-bottom: 1px solid #f0f0f0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchResult li:last-child {\n");
      out.write("	border-bottom: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: inherit;\n");
      out.write("}\n");
      out.write(".header-flex {\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction : row;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	padding : 10px 40px;\n");
      out.write("}\n");
      out.write(".header-left {\n");
      out.write("	color: #007bff;\n");
      out.write("}\n");
      out.write(".header-right {\n");
      out.write("	display:flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	align-items: flex-start;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	border: 1px #007bff solid;\n");
      out.write("	padding: 10px;\n");
      out.write("	margin-left: 10%;\n");
      out.write("}\n");
      out.write(".header-menu {\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: row;\n");
      out.write("	align-content: flex-start;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	margin-top: 10px;\n");
      out.write("}\n");
      out.write(".logo {\n");
      out.write("    height: 170px;\n");
      out.write("    width: 300px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"searchAPI.js\"></script>\n");
      out.write("<header>\n");
      out.write("<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("<div class=\"header-flex\">\n");
      out.write("	<div class=\"header-left\">\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/main-page.bo\"><img class=\"logo\" alt=\"메인페이지로 이동\" src=\"../img/ksw.png\"></a>\n");
      out.write("	</div>\n");
      out.write("	<form id=\"searchFrm\">\n");
      out.write("		<div>\n");
      out.write("			<input type=\"text\" name=\"search\" id=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyward }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("				placeholder=\"검색하실 책 제목을 입력하세요\" >\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			<button type=\"button\" id=\"searchBtn\">검색</button>\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div>\n");
      out.write("<nav>\n");
      out.write("<ul class=\"nav-bar\">\n");
      out.write("	<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/main-page.bo\">메인 페이지</a></li>\n");
      out.write("	<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notice-main.bo\">고객센터</a></li>\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("</header>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<form action=\"\">\n");
      out.write("		<div class=\"row\" id=\"searchResult\"></div>\n");
      out.write("	</form>\n");
      out.write("	<div id=\"pagination\">\n");
      out.write("		<!-- 페이지네이션 버튼이 여기에 들어갑니다 -->\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /search/searchview.jsp(188,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userid}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class=\"header-right\">\n");
          out.write("				<div>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 안녕하세요.</div>\n");
          out.write("				<div class=\"header-menu\" >\n");
          out.write("					<div style=\"margin-right: 20px;\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login/LogOut.bo\">로그아웃</a></div>\n");
          out.write("					<div><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/myPage/myPage.bo\">마이페이지</a></div>\n");
          out.write("				</div>\n");
          out.write("			</div>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class=\"header-right\">\n");
          out.write("				<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login/Sign-up-in.bo\">로그인</a>\n");
          out.write("			</div>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
